apiVersion: v1
kind: Pod
metadata:
  name: ecal-finetune-g4pb
  namespace: ai4phys
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 255610
    runAsGroup: 50027
    fsGroup: 50027
  containers:
    - name: mecontainer
      image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel
      volumeMounts:
        - name: nsf
          mountPath: /sciclone/home/jgiroux # Your username
        - name: d10
          mountPath: /sciclone/data10/jgiroux/ # Your username
        - name: scr30
          mountPath: /sciclone/scr30/jgiroux # Your username
      command:
        - /bin/bash
        - -c
        - |
          export PYTHONUNBUFFERED=1
          export OMP_NUM_THREADS=2
          eval "$(conda shell.bash hook)"
          conda activate /sciclone/home/jgiroux/.conda/envs/torch_linux
          torchrun --nproc-per-node=2 /sciclone/home/jgiroux/FM4CAL/fine_tune.py --config /sciclone/home/jgiroux/FM4CAL/config/CA_config_dist_copy.json --default_material_list "G4_W_gamma" "G4_Ta_gamma" --material_to_add "G4_Pb_gamma" --closest_expert "G4_Ta_gamma" --fine_tune_path TO_ADD > /sciclone/scr30/jgiroux/FM4CAL/TrainLogs/FineTuning_W_Ta_with_Pb_35MeVTokens_2100MSL.txt  2>&1
      resources:
        requests:
          cpu: "30"
          memory: "120Gi"
          nvidia.com/gpu: "2"
        limits:
          cpu: "30"
          memory: "120Gi"
          nvidia.com/gpu: "2"
      securityContext:
        runAsUser: 255610
        runAsGroup: 50027
  tolerations:
    - key: "node"
      operator: "Equal"
      value: aiphys
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: aiphys-node1.sciclone.wm.edu
    nvidia.com/gpu.product: "NVIDIA-L40S"
  volumes:
    - name: nsf
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/jgiroux # Your username
    - name: d10
      nfs:
        server: 128.239.56.30
        path: /sciclone/data10/jgiroux # Your username
    - name: scr30
      nfs:
        server: 128.239.56.174
        path: /sciclone/scr30/jgiroux # Your username
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi