apiVersion: v1
kind: Pod
metadata:
  name: dora-the-explorer
  namespace: ai4phys
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 255610
    runAsGroup: 50027
    fsGroup: 50027
  containers:
    - name: mecontainer
      image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime #pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel
      volumeMounts:
        - name: nsf
          mountPath: /sciclone/home/jgiroux # Your username
        - name: d10
          mountPath: /sciclone/data10/jgiroux/ # Your username
        - name: scr30
          mountPath: /sciclone/scr30/jgiroux # Your username
        - name: scr10
          mountPath: /sciclone/scr10/jgiroux # Your username
        - name: dshm
          mountPath: /dev/shm
      command:
        - /bin/bash
        - -c
        - |
          export PYTHONUNBUFFERED=1
          export OMP_NUM_THREADS=2
          eval "$(conda shell.bash hook)"
          conda activate /sciclone/home/jgiroux/.conda/envs/torch_linux
          torchrun --nproc-per-node=4 /sciclone/home/jgiroux/FM4CAL/fine_tune.py --config /sciclone/home/jgiroux/FM4CAL/config/CA_config_dist_copy.json --default_material_list "G4_W_gamma" "G4_Ta_gamma" --material_to_add "G4_W_e-" --closest_expert "G4_W_gamma" --base_particle_list "gamma" --particle_type "e-" --fine_tune_path /sciclone/data10/jgiroux/ECAL_Cole/ECAL_Models/1MillSample_35MeVTokens_MultiStepLR_2100MSL___Jan-14-2026/Epoch11_loss_9.718361.pth > /sciclone/scr30/jgiroux/FM4CAL/TrainLogs/DoRA_DualVocab_Rank16_e-.txt 2>&1
      resources:
        requests:
          cpu: "31"
          memory: "250Gi"
          nvidia.com/gpu: "4"
        limits:
          cpu: "31"
          memory: "250Gi"
          nvidia.com/gpu: "4"
      securityContext:
        runAsUser: 255610
        runAsGroup: 50027
  nodeSelector:
    kubernetes.io/hostname: ts4.sciclone.wm.edu
    nvidia.com/gpu.product: "Quadro-RTX-6000"
  volumes:
    - name: nsf
      nfs:
        server: 128.239.56.166 
        path: /sciclone/home/jgiroux # Your username
    - name: d10
      nfs:
        server: 128.239.56.30 
        path: /sciclone/data10/jgiroux # Your username
    - name: scr10
      nfs:
        server: 128.239.56.168
        path: /sciclone/scr10/jgiroux # Your username
    - name: scr30
      nfs:
        server: 128.239.56.174 
        path: /sciclone/scr30/jgiroux # Your username
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 4Gi